[kivy_reloader]

# The IP address of your phone; You can hot-reload how many phones you want.
# use "127.0.0.1" if you are using Android emulator.
PHONE_IPS = ["192.168.1.68"]

# If true, it's going to send the app to smartphone every time you press Ctrl+S
HOT_RELOAD_ON_PHONE = false

# You can stream using "USB" or "WIFI"
# If your USB cable is connected, use "USB", otherwise use "WIFI"
# To use WIFI, you need connect your phone to the same network as your computer
STREAM_USING = "USB"

# The port where the server will be listening
# It can be any port
PORT = 5555

# Add the files that will cause the app to live reload (restart) when changed
FULL_RELOAD_FILES = ["main.py"]

# Add the python files you want to watch here, i.e., if they change, the app will hot reload
WATCHED_FILES = []

# Add the folders you want to watch recursively here, i.e., if **ANY FILE** inside them changes, the app will hot reload
WATCHED_FOLDERS_RECURSIVELY = []

# Watched folders but not recursively, i.e., **ANY FILE** inside the first level of the folder will trigger a hot reload if changed
WATCHED_FOLDERS = []

# If you do not want to watch some files or folders, add them here.
# You can add the path to a file/folder or a pattern
DO_NOT_WATCH_PATTERNS = ["*.pyc", "*__pycache__*"]

# If you want to logcat services, put here the name of each service
# For example, ["MyService", "MyOtherService"]
SERVICE_NAMES = []

# If you want to restart your app when your services change, put the relative path of the service files here
# For example, ["service.py", "service2.py"]
SERVICE_FILES = []

# If you want to exclude some files or folders, from being copied to the phone, add them here
FOLDERS_AND_FILES_TO_EXCLUDE_FROM_PHONE = [
    "*.pyc",
    "__pycache__",
    ".buildozer",
    ".venv",
    ".vscode",
    ".git",
    ".pytest_cache",
    ".DS_Store",
    ".env",
    ".dmypy.json",
    ".mypy_cache/",
    ".dmypy.json",
    "dmypy.json",
    "env/",
    "ENV/",
    "env.bak/",
    "venv/",
    "venv.bak/",
    "bin",
    "dist",
    "buildozer.spec",
    "poetry.lock",
    "pyproject.toml",
    "temp",
    "tests",
    "app_copy.zip",
    "send_app_to_phone.py",
    ".gitignore",
    "README.md",
]

# The X position of the window generated by scrcpy
WINDOW_X = "1200"

# The Y position of the window generated by scrcpy
WINDOW_Y = "100"

# The width of the window generated by scrcpy
WINDOW_WIDTH = "280"

# The title of the window generated by scrcpy
WINDOW_TITLE = "Kivy Reloader"

# If you want to show the touches on the screen, set this to True
SHOW_TOUCHES = false

# If you want the screen to be always on, set this to True
STAY_AWAKE = false

# If you want to turn the screen off, set this to True
TURN_SCREEN_OFF = false

# If you want the window to be always on top, set this to True
ALWAYS_ON_TOP = true

# If you want to turn the audio off, set this to True
NO_AUDIO = true
