name: create iOS Wheels


on: 
  #- push
  #- pull_request
  - workflow_dispatch


jobs:
  create-ios-wheels:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: pip installs
      run: |
        pip install toml
    
    - name: Modify dependencies
      run: |
        python .ci/modify_ios.py
        echo "$(pyproject.toml)"
